bundler_args: --without development
language: ruby
rvm:
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: rbx-18mode
    - rvm: 1.8.7
    - rvm: 2.1.0
env:
  - "RAILS_VERSION=2.3.2"
  - "RAILS_VERSION=3.0.20"
  - "RAILS_VERSION=3.1.12"
  - "RAILS_VERSION=3.2.15"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=master"
